workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
stages:
  - lintstage
  - build
  - test
  - pull_image
lintstage-Lint:
  image: ubuntu:latest
  stage: lintstage
  script: []
  needs: []
build-Checkout:
  image: ubuntu:latest
  stage: build
  script: []
  needs: []
build-build_docker_image:
  image: ubuntu:latest
  stage: build
  script: []
  needs: []
  services:
    - docker:dind
test-Unit_test:
  image: ubuntu:latest
  stage: test
  script: []
  needs:
    - lintstage-Lint
    - build-Checkout
    - build-build_docker_image
pull_image-pull_image_from_dockerHub:
  image: ubuntu:latest
  stage: pull_image
  script: []
  needs: []
