workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
stages:
  - lintstage
  - build
  - test
  - lintstage
  - build
  - test
lintstage-job-1:
  image: ubuntu:latest
  stage: lintstage
  script:
    - apt-get update -y
    - apt-get install -y nodejs npm
    - npm install
    - npm run lint
  needs: []
build-job-1:
  image: ubuntu:latest
  stage: build
  script:
    - echo "ANOTHER GREAT SUCCESS"
  needs: []
build-job-2:
  image: ubuntu:latest
  stage: build
  script:
    - docker login -u GenericDockerUserName -p $docker-password
    - docker build -t ubuntu ./Dockerfile
    - docker push GenericDockerUserName/ubuntu
  needs: []
  services:
    - docker:dind
test-job-1:
  image: ubuntu:latest
  stage: test
  script:
    - npm install
    - npm test
  needs:
    - lintstage-job-1
    - build-job-1
    - build-job-2
