workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
stages:
  - lintstage
  - buildstage
lintstage-Lint:
  image: ubuntu:latest
  stage: lintstage
  script:
    - apt-get update -y
    - apt-get install -y nodejs
    - npm install
    - npm run lint
  needs: []
buildstage-build:
  image: ubuntu:latest
  stage: buildstage
  script:
    - echo build done
  needs:
    - lintstage-Lint
