workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
stages:
  - lintstage
  - build
  - test
  - pull_image
  - custom image stage
lintstage-Lint:
  image: ubuntu:latest
  stage: lintstage
  script:
    - apt-get update -y
    - apt-get install -y nodejs
    - npm install
    - npm run lint
  needs: []
build-Checkout:
  image: ubuntu:latest
  stage: build
  script:
    - echo "ANOTHER GREAT SUCCESS"
  needs: []
build-build_docker_image:
  image: ubuntu:latest
  stage: build
  script:
    - docker login -u GenericDockerUserName -p $docker-password
    - docker build -t SingularCI_TestingImage ./Dockerfile
    - docker push GenericDockerUserName/SingularCI_TestingImage
  needs: []
  services:
    - docker:dind
test-Unit_test:
  image: ubuntu:latest
  stage: test
  script:
    - npm install
    - npm test
  needs:
    - lintstage-Lint
    - build-Checkout
    - build-build_docker_image
pull_image-pull_image_from_dockerHub:
  image: ubuntu:latest
  stage: pull_image
  script:
    - docker login -u GenericDockerUserName -p $docker-password
    - docker pull GenericDockerUserName/SingularCI_TestingImage
  needs: []
custom image stage-custom_image_job:
  image: node:16
  stage: custom image stage
  script:
    - echo "Im a custom image job"
  needs: []
