pipeline:
  targets:
    - GitHub
    - GitLab

  variables:
    - key: repo-name
      value: ${secrets.super-secret-repo-name}
    - key: docker-username
      value: GenericDockerUserName
    - key: image_name
      value: SingularCI_TestingImage

  triggers: 
    trigger_types:
      - push
      - pull_request
    branches:
      - master
      - main
      - refactor
  
  stages:

    - stage:
        name: lintstage
        runs_on: ubuntu-latest
        jobs:
          - name: Lint
            run: 
              - apt-get update -y
              - apt-get install -y nodejs
              - npm install
              - npm run lint
    - stage:
        name: build
        runs_on: ubuntu-latest
        jobs:
          - name: Checkout
            run: 
              - echo "ANOTHER GREAT SUCCESS"
          - name: build docker image
            docker_build:
              image_name: ${image_name}
              docker_file_path: ./Dockerfile 
              user_name: ${docker-username}
              password: ${secrets.docker-password}
    
    - stage:
        name: test
        needs: [lintstage, build]
        runs_on: ubuntu-latest
        jobs:
          - name: Unit test
            run: 
              - npm install
              - npm test
    - stage:
        name: pull_image
        runs_on: ubuntu-latest
        jobs:
          - name: pull image from dockerHub
            docker_pull:
              image_name: ${docker-username}/${image_name}
              user_name: ${docker-username}
              password: ${secrets.docker-password}
    - stage:
        name: custom image stage
        runs_on: node:16
        jobs:
          - name: custom image job
            run: 
              - echo "Im a custom image job"