pipeline:
  targets:
    - GitHub
    - GitLab

  variables:
    - key: repo-name
      value: ${secrets.super-secret-repo-name}
    - key: docker-username
      value: GenericDockerUserName

  triggers: 
    trigger_types:
      - push
      - pull_request
    branches:
      - master
      - main
  
  stages:

    - stage:
        name: lintstage
        runs_on: windows-latest
        jobs:
          - name: Lint
            run: 
              - lint_this_project.exe
              - this_is_the_second_command.exe

    - stage:
        name: build
        runs_on: ubuntu-latest
        jobs:
          - name: Checkout
            run: 
              - this_is_a_checkout_command.sh
          - name: build docker image for ${repo-name}
            docker_build:
              image_name: ubuntu
              docker_file_path: ./Dockerfile 
              user_name: ${docker-username}
              password: ${secrets.docker-password}
    
    - stage:
        name: test
        needs: [lintstage, build]
        runs_on: ubuntu-latest
        jobs:
          - name: Unit test
            run: 
              - npm test
            