pipeline:
  targets:
    - GitHub

  variables:
    - key: repo-name
      value: ${secrets.repo-asdfjasdf}
    - key: wakawaka-name
      value: secrets.wakawaka-name

  triggers: 
    trigger_types:
      - push
      - pull_request
    branches:
      - master
      - main
  
  stages:
    - stage:
        name: build
        runs_on: ubuntu
        job:
          - name: ${secrets.hakuna-matata}
            run: this is a checkout command ${secrets.wakawaka-name} ${secrets.wako-bako}
          - name: build docker image for ${repo-name}
            docker_build:
              image_name: ubuntu
              docker_file_path: ./Dockerfile 
    
    - stage:
        name: test
        runs_on: ubuntu
        job:
          - name: test
            run: this is a test command