pipeline:
  targets:
    - GitHub

  variables:
    - key: docker_username
      value: saibotv2
    - key: image_name
      value: singularci

  triggers: 
    trigger_types:
      - push
      - pull_request
    branches:
      - master
      - main
  
  stages:

    - stage:
        name: lint
        runs_on: node:16
        jobs:
          - name: checkout repository
            checkout: Tobiaskr12/SingularCI
          - name: run eslint
            run: 
              - npm install
              - npm run lint

    - stage:
        name: test
        needs: [lint]
        runs_on: ubuntu-latest
        jobs:
          - name: checkout repository
            checkout: Tobiaskr12/SingularCI
          - name: Unit test
            run: 
              - npm install
              - npm test
    