pipeline:
  targets:
    - GitHub
    - GitLab

  variables:
    - key: docker_username
      value: saibotv2
    - key: image_name
      value: singularci-test

  triggers: 
    trigger_types:
      - push
      - pull_request
    branches:
      - master
      - main
  
  stages:

    - stage:
        name: lint
        runs_on: node:16
        jobs:
          - name: checkout repository and run eslint
            checkout: 
              repo_url: https://github.com/Tobiaskr12/SingularCI.git
              repo_name: SingularCI
            run: 
              - npm install
              - npm run lint

    - stage:
        name: test
        needs: [lint]
        runs_on: ubuntu-latest
        jobs:
          - name: checkout repository and run tests
            checkout: 
              repo_url: https://github.com/Tobiaskr12/SingularCI.git
              repo_name: SingularCI
            run: 
              - npm install
              - npm test

    - stage:
        name: docker_build
        needs: [test]
        runs_on: ubuntu-latest
        jobs:
          - name: execute docker build
            docker_build:
              image_name: ${image_name}
              docker_file_path: ./ 
              user_name: ${docker_username}
              password: ${secrets.DOCKER_PASSWORD}
    