pipeline:
  targets:
    - GitHub

  variables:
    - key: docker_username
      value: saibotv2
    - key: image_name
      value: singularci

  triggers: 
    trigger_types:
      - push
      - pull_request
    branches:
      - master
      - main
  
  stages:

    - stage:
        name: lint
        runs_on: node:16
        jobs:
          - name: checkout repository
            checkout: Tobiaskr12/SingularCITestProject
          - name: run eslint
            run: 
              - npm install
              - npm run lint

    - stage:
        name: test
        needs: [lintstage, build]
        runs_on: ubuntu-latest
        jobs:
          - name: Unit test
            run: 
              - npm install
              - npm test

    - stage:
        name: build
        runs_on: ubuntu-latest
        jobs:
          - name: execute docker build
            docker_build:
              image_name: ${image_name}
              docker_file_path: ./ 
              user_name: ${docker_username}
              password: ${secrets.DOCKER_PASSWORD}
    