pipeline:
  targets:
    - GitHub
    - GitLab

  variables:
    - key: repo-name
      value: Hennings-Herlige-Repo
    - key: wakawaka-name
      value: ${secrets.wakawaka-name}

  triggers: 
    trigger_types:
      - push
      - pull_request
    branches:
      - master
      - main
  
  stages:
    - stage:
        name: build
        runs_on: ubuntu
        job:
          - name: checkout repo
            run: this is a checkout command
          - name: build docker image
            docker_build:
              image_name: ubuntu
              docker_file_path: ./Dockerfile
    
    - stage:
        name: test
        runs_on: ubuntu
        job:
          - name: test
            run: this is a test command