pipeline:
  targets:
    - GitHub
    - GitLab

  variables:
    - key: repo-name
      value: Hennings-Herlige-Repo
    - key: wakawaka-name
      value: ${secrets.wakawaka-name}

  triggers: 
    trigger-types:
      - push
      - pull_request
    branches:
      - master
      - main
  
  stages:
    - stage:
        name: build
        runs-on: ubuntu
        job:
          - name: checkout repo
            run: this is a checkout command
          - name: build docker image
            docker-build:
              docker-file-path: ./Dockerfile
    
    - stage:
        name: test
        runs-on: ubuntu
        job:
          - name: test
            run: this is a test command